"""Pins for scripts/readme_hero.py — the púca drawn from its own block art, honest
chips, and an SVG GitHub will actually animate inside an <img>."""
from __future__ import annotations

import importlib.util
import re
import xml.etree.ElementTree as ET
from pathlib import Path

import pytest

from puca.report import owasp

ROOT = Path(__file__).resolve().parents[1]
_spec = importlib.util.spec_from_file_location("readme_hero", ROOT / "scripts/readme_hero.py")
assert _spec and _spec.loader
hero = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(hero)


# ── The púca ───────────────────────────────────────────────────────────────

def test_every_block_character_is_two_square_half_cells():
    rows = hero.parse_block_art("█▄▀▘ ⠀")
    assert rows == ["#.##..", "##...."]


def test_an_unknown_block_character_is_refused():
    with pytest.raises(ValueError, match="no half-cell mapping"):
        hero.parse_block_art("█▌")


def test_the_mark_is_the_readme_puca_on_a_16_by_30_grid():
    text = hero.MARK.read_text()
    assert len([ln for ln in text.splitlines() if ln.strip(" ⠀")]) == 15
    rows = hero.parse_block_art(text)
    assert (len(rows), len(rows[0])) == (30, 16)


def test_only_enclosed_holes_become_eyes():
    puca = hero.eyes(hero.parse_block_art(hero.MARK.read_text()))
    eye_rows = {r for r, row in enumerate(puca) if "o" in row}
    assert eye_rows == set(range(10, 16))            # the two eye slots, not the gaps between the legs
    assert all("o" not in row for row in puca[24:])


def test_the_loop_opens_and_holds_longest_on_the_puca():
    puca = hero.eyes(hero.parse_block_art(hero.MARK.read_text()))
    seq = hero.sequence(puca)
    assert seq[0][0] == puca
    holds = [secs for _, flight, secs in seq if not flight]
    assert seq[0][2] == max(holds)


def test_every_form_stands_on_the_pucas_grid_with_eyes():
    puca = hero.eyes(hero.parse_block_art(hero.MARK.read_text()))
    for form in (hero.HARE, hero.GOAT, hero.DOG):
        assert (len(form), len(form[0])) == (len(puca), len(puca[0]))
        assert all(len(row) == 16 for row in form)
        assert "#" in form[28] and set(form[29]) == {"."}   # feet on the same row
        assert any("o" in row for row in form)


# ── Honest chips ───────────────────────────────────────────────────────────

def test_each_catalogue_chip_is_a_catalogue_the_code_carries():
    assert "OWASP Web Top 10" in hero.CHIPS and owasp.WEB_TOP_10_2021
    assert "LLM Top 10 (2026)" in hero.CHIPS and owasp.LLM_TOP_10_2026
    assert "Agentic ASI01–ASI10" in hero.CHIPS
    assert {f"ASI{n:02d}" for n in range(1, 11)} <= set(owasp.AGENTIC_TOP_10_2026)
    # No API Top 10 catalogue exists in puca/report/owasp.py, so no chip may claim one.
    assert not any("API Top" in chip for chip in hero.CHIPS)


def test_the_lead_chip_is_the_one_rule():
    assert hero.CHIPS[0] == "No scope, no fire"


# ── The committed SVG ──────────────────────────────────────────────────────

def _svg() -> str:
    return hero.OUTPUT.read_text()


def test_the_readme_shows_the_svg_hero():
    readme = (ROOT / "README.md").read_text()
    assert 'src="assets/hero.svg"' in readme


def test_the_committed_svg_is_well_formed_and_github_safe():
    svg = _svg()
    ET.fromstring(svg)                                   # a malformed SVG renders as nothing
    assert "<script" not in svg
    assert not re.search(r'(href|src)\s*=\s*["\']https?:|url\(\s*["\']?https?:|@import', svg)
    assert svg.count("data:font/woff2;base64,") == 2
    assert f'viewBox="0 0 {hero.W} {hero.H}"' in svg
    assert "<title" in svg and "<desc" in svg


def test_the_committed_svg_carries_every_line_the_generator_writes():
    svg = _svg()
    for line in [hero.EYEBROW, hero.TITLE, hero.TAGLINE, hero.LABEL, *hero.CHIPS]:
        assert line in svg, line
    assert 'class="chip lead"' in svg
    assert "Generated by scripts/readme_hero.py" in svg


def test_the_committed_svg_honours_reduced_motion():
    block = _svg().split("prefers-reduced-motion:reduce", 1)[1]
    assert "animation:none" in block
    assert ".s0{opacity:1}" in block                     # the púca, standing still
    assert ".probe,.hit,.deny{opacity:0}" in block       # and no probes in flight


def test_the_committed_svg_stays_inside_its_budget():
    assert hero.OUTPUT.stat().st_size < 400_000


def test_the_committed_svg_is_exactly_what_the_generator_builds():
    """Byte-for-byte (the font subsets' timestamps are pinned). Skipped where fonttools
    isn't installed, as in CI; run it locally after any edit."""
    pytest.importorskip("fontTools")
    pytest.importorskip("brotli")
    assert hero.build() == _svg()
